2025-01-15 05:19:27,054:DEBUG:certbot._internal.main:certbot version: 3.1.0
2025-01-15 05:19:27,054:DEBUG:certbot._internal.main:Location of certbot entry point: .venv/bin/certbot
2025-01-15 05:19:27,054:DEBUG:certbot._internal.main:Arguments: ['--dns-digitalocean', '--dns-digitalocean-credentials', './digitalocean.ini', '--dns-digitalocean-propagation-seconds', '60', '-d', 'gh40.xyz', '--non-interactive', '--agree-tos', '-m', 'ryantiffany@fastmail.com', '--config-dir', './', '--logs-dir', './', '--work-dir', './']
2025-01-15 05:19:27,054:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-digitalocean,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-01-15 05:19:27,068:DEBUG:certbot._internal.log:Root logging level set at 30
2025-01-15 05:19:27,068:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-digitalocean and installer None
2025-01-15 05:19:27,068:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-digitalocean
Description: Obtain certificates using a DNS TXT record (if you are using DigitalOcean for DNS).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='dns-digitalocean', value='certbot_dns_digitalocean._internal.dns_digitalocean:Authenticator', group='certbot.plugins')
Initialized: <certbot_dns_digitalocean._internal.dns_digitalocean.Authenticator object at 0x100454080>
Prep: True
2025-01-15 05:19:27,068:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_digitalocean._internal.dns_digitalocean.Authenticator object at 0x100454080> and installer None
2025-01-15 05:19:27,068:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-digitalocean, Installer None
2025-01-15 05:19:27,168:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-01-15 05:19:27,171:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-01-15 05:19:27,321:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/11" 200 828
2025-01-15 05:19:27,322:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 15 Jan 2025 11:19:27 GMT
Content-Type: application/json
Content-Length: 828
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "The same profile you're accustomed to"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "pBvtQD7XyW4": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-01-15 05:19:27,322:DEBUG:acme.client:Requesting fresh nonce
2025-01-15 05:19:27,322:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-01-15 05:19:27,368:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/11" 200 0
2025-01-15 05:19:27,369:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 15 Jan 2025 11:19:27 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 5VsalEMJFe9aNSebNqhFVVkd-wph4GbTlYL9OwW-ZI5bpMmSJLQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-01-15 05:19:27,369:DEBUG:acme.client:Storing nonce: 5VsalEMJFe9aNSebNqhFVVkd-wph4GbTlYL9OwW-ZI5bpMmSJLQ
2025-01-15 05:19:27,369:DEBUG:acme.client:JWS payload:
b'{\n  "contact": [\n    "mailto:ryantiffany@fastmail.com"\n  ],\n  "termsOfServiceAgreed": true\n}'
2025-01-15 05:19:27,382:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogInQzbGZ4c1gxVkpyVEdRZDhRdmsxb1lpZEUwbW82NUJ5MFhZYUE3QzItOEdRTDJOTFNINzJVUzRsemxSUmFxc3ZyTk9md2JMQWxvcldoWWE5SUNHQWk5dnBiai1uaDNIWWwwTWIyUmMxaGYwaTNrdXNYUWhiMzZkTVQ3RDBhRC02NDVIcUVLcU5GSHd3Wjk5ZF9mTGFaWVNuWGpjek5FWGJVRS1rMEhqSzJKTlp2dXhldnl1akV2YzlYc0N0RUpWb1gwdGxEdk5NXzk5aHJkZ0Z0MDJjcjhxUXhKbWtockFqeko3Q3AtQkdVSnB1djJ0ekR5bE1kSWxWZ3pkd1dDT2VZazQtRS1TQkRQU0FuVUc4Y2I2dURFNTNtRWxTSmJGNVg2Nzl3ZDlhY1l3ZzR5M25ONTR3LXZSbWlsdldXYmgzX1BnSzFHWGtsZU1mdTl5bFQzcGNtdyIsICJlIjogIkFRQUIiLCAia3R5IjogIlJTQSJ9LCAibm9uY2UiOiAiNVZzYWxFTUpGZTlhTlNlYk5xaEZWVmtkLXdwaDRHYlRsWUw5T3dXLVpJNWJwTW1TSkxRIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctYWNjdCJ9",
  "signature": "LoKcSJHqmncBHbOSWl_CXy2eQ08P2Kir5qakyfOHKzc39KDHC17KfKAmff8V97WaEPGcyitc3sSO-tkjx8UnAHsSI05zAwAS_pYRJMWVAVPHeudvp1xKUIaNIucCdOixNTZzWRGKAIIKHncgBLcQy7vR3kYOc5LadKKyNibgoXijJgxbWIrNLV7bQCGq6RTxw82AvuapBODJo2hF6GFH8amyEXGHJD9fW5zOp3ithQW1FIaZt77iacgOlZiTiKpDRF5XMKloUs8Zsfag4XZEfvoIxz6gcKsTt8Em5-RLqGuq6n7Zfs_117CyKYIOoetLH_0t8rmRkRjDlck-RGWgcw",
  "payload": "ewogICJjb250YWN0IjogWwogICAgIm1haWx0bzpyeWFudGlmZmFueUBmYXN0bWFpbC5jb20iCiAgXSwKICAidGVybXNPZlNlcnZpY2VBZ3JlZWQiOiB0cnVlCn0"
}
2025-01-15 05:19:27,465:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-acct HTTP/11" 201 535
2025-01-15 05:19:27,466:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 15 Jan 2025 11:19:27 GMT
Content-Type: application/json
Content-Length: 535
Connection: keep-alive
Boulder-Requester: 2171495035
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf>;rel="terms-of-service"
Location: https://acme-v02.api.letsencrypt.org/acme/acct/2171495035
Replay-Nonce: 5VsalEMJEsMgN2z-VQDJAKT9YbHaQWjmu3i0i5lpwprUWJ6afgo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "key": {
    "kty": "RSA",
    "n": "t3lfxsX1VJrTGQd8Qvk1oYidE0mo65By0XYaA7C2-8GQL2NLSH72US4lzlRRaqsvrNOfwbLAlorWhYa9ICGAi9vpbj-nh3HYl0Mb2Rc1hf0i3kusXQhb36dMT7D0aD-645HqEKqNFHwwZ99d_fLaZYSnXjczNEXbUE-k0HjK2JNZvuxevyujEvc9XsCtEJVoX0tlDvNM_99hrdgFt02cr8qQxJmkhrAjzJ7Cp-BGUJpuv2tzDylMdIlVgzdwWCOeYk4-E-SBDPSAnUG8cb6uDE53mElSJbF5X679wd9acYwg4y3nN54w-vRmilvWWbh3_PgK1GXkleMfu9ylT3pcmw",
    "e": "AQAB"
  },
  "contact": [
    "mailto:ryantiffany@fastmail.com"
  ],
  "createdAt": "2025-01-15T11:19:27.469076493Z",
  "status": "valid"
}
2025-01-15 05:19:27,466:DEBUG:acme.client:Storing nonce: 5VsalEMJEsMgN2z-VQDJAKT9YbHaQWjmu3i0i5lpwprUWJ6afgo
2025-01-15 05:19:27,471:DEBUG:certbot._internal.display.obj:Notifying user: Account registered.
2025-01-15 05:19:27,471:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.bindings._rust.openssl.rsa.RSAPublicKey object at 0x102ecf7b0>)>), contact=('mailto:ryantiffany@fastmail.com',), agreement=None, status='valid', terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2171495035', new_authzr_uri=None, terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf'), 7fe19b0298363bb6f3b3af0c19b14481, Meta(creation_dt=datetime.datetime(2025, 1, 15, 11, 19, 27, tzinfo=<UTC>), creation_host='1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa', register_to_eff=None))>
2025-01-15 05:19:27,473:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for gh40.xyz
2025-01-15 05:19:27,480:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "gh40.xyz"\n    }\n  ]\n}'
2025-01-15 05:19:27,483:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE3MTQ5NTAzNSIsICJub25jZSI6ICI1VnNhbEVNSkVzTWdOMnotVlFESkFLVDlZYkhhUVdqbXUzaTBpNWxwd3ByVVdKNmFmZ28iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "my6wi4CsvS7PNDq5PWYUhbx0AOgmB-sPLjhqY1EB-Vq1QSTO-YEiiPnIGk3emONOy_7lRSdI6DOCEaq5ydKv9ouRS1EYGE36X03lLNII9Mrh01x55a0c--Nyhg2I7eRinaBdH3aNoLJg05Cp0VC_JlLc8RGZMHZ0wGOAeNjMjIteqluV9kqHJtx7tIO6N6FbR_8zDnpQrFsZt_2bPcR7IhW9y6nLeAtq364RPH9RGIdFinV2vImbRDkFxYtEJbY1H4B1jn2p5cW4GhLu9Fg0BBFY6Kous-4AKrhjr0bIui1i2dBh2hL803KbZWJhUn_dno_-oPUq0SpJ5kd68n2ueA",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImdoNDAueHl6IgogICAgfQogIF0KfQ"
}
2025-01-15 05:19:27,577:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/11" 201 342
2025-01-15 05:19:27,578:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 15 Jan 2025 11:19:27 GMT
Content-Type: application/json
Content-Length: 342
Connection: keep-alive
Boulder-Requester: 2171495035
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2171495035/344601016035
Replay-Nonce: 5VsalEMJhfW9XVhcR8hRHJ2MuUzxb9mGu2d0uyGMT9BYc9LlMOc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2025-01-22T11:19:27Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "gh40.xyz"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2171495035/461015138555"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2171495035/344601016035"
}
2025-01-15 05:19:27,578:DEBUG:acme.client:Storing nonce: 5VsalEMJhfW9XVhcR8hRHJ2MuUzxb9mGu2d0uyGMT9BYc9LlMOc
2025-01-15 05:19:27,579:DEBUG:acme.client:JWS payload:
b''
2025-01-15 05:19:27,583:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2171495035/461015138555:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE3MTQ5NTAzNSIsICJub25jZSI6ICI1VnNhbEVNSmhmVzlYVmhjUjhoUkhKMk11VXp4YjltR3UyZDB1eUdNVDlCWWM5TGxNT2MiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxNzE0OTUwMzUvNDYxMDE1MTM4NTU1In0",
  "signature": "XZjR2FD61UTolnsKATlsc0dZzT-9Bnj7R1dkLISGPDhWuZcJibK0gH1NsNn6yvTkuKq5rJ5k8uFCKKwvzYhFKsVqHU7A0F9V-ajyNfgiQenUjsfO7JZyA5XNlq5WwfEp3yiuI0tS7FKmzDiTUepYUFDH99fuwtJB4i5tTetWeTi7h4ESW5mqfZ5fWIh7-Jni6Eb8KBtNTIdnHie_a6OJispvSCFsw-CcNflMdmPv_hSlOOQdsVWQuJTuR8G_dL5QxJHZCFQllBZmQrQOOQyDR_QH3yb-hzYp9kfaSgpW897RTb9-dtwTqJMaR5qB2ZT0PT6SoLw9C8OZRdlLacOzAg",
  "payload": ""
}
2025-01-15 05:19:27,630:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2171495035/461015138555 HTTP/11" 200 816
2025-01-15 05:19:27,631:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 15 Jan 2025 11:19:27 GMT
Content-Type: application/json
Content-Length: 816
Connection: keep-alive
Boulder-Requester: 2171495035
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 5VsalEMJ_OX71bjrDH_hUPuAq4Vz0ex9x2xy0fiWuOXq_-QGCS0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "gh40.xyz"
  },
  "status": "pending",
  "expires": "2025-01-22T11:19:27Z",
  "challenges": [
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2171495035/461015138555/JJEFgA",
      "status": "pending",
      "token": "66n-H5IdkEK2Stkfp5ULiBdx0Wt9WnUr531UC__T3EI"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2171495035/461015138555/xU1sTA",
      "status": "pending",
      "token": "66n-H5IdkEK2Stkfp5ULiBdx0Wt9WnUr531UC__T3EI"
    },
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2171495035/461015138555/McE81g",
      "status": "pending",
      "token": "66n-H5IdkEK2Stkfp5ULiBdx0Wt9WnUr531UC__T3EI"
    }
  ]
}
2025-01-15 05:19:27,631:DEBUG:acme.client:Storing nonce: 5VsalEMJ_OX71bjrDH_hUPuAq4Vz0ex9x2xy0fiWuOXq_-QGCS0
2025-01-15 05:19:27,631:INFO:certbot._internal.auth_handler:Performing the following challenges:
2025-01-15 05:19:27,631:INFO:certbot._internal.auth_handler:dns-01 challenge for gh40.xyz
2025-01-15 05:19:27,633:DEBUG:digitalocean:GET https://api.digitalocean.com/v2/domains/ params:{'per_page': 200} {'Content-type': 'application/json', 'Authorization': 'Bearer TOKEN0', 'User-Agent': 'python-digitalocean/1.16.0 requests/2.32.3'} None
2025-01-15 05:19:27,635:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.digitalocean.com:443
2025-01-15 05:19:27,953:DEBUG:urllib3.connectionpool:https://api.digitalocean.com:443 "GET /v2/domains/?per_page=200 HTTP/11" 200 None
2025-01-15 05:19:27,957:DEBUG:certbot_dns_digitalocean._internal.dns_digitalocean:Found base domain for gh40.xyz using name gh40.xyz
2025-01-15 05:19:27,957:DEBUG:digitalocean:POST https://api.digitalocean.com/v2/domains/gh40.xyz/records data:{'type': 'TXT', 'name': '_acme-challenge', 'data': '7VL8i8WJFVs4R7U450RC1QBFLvd5L-Ohmv6FOMaDBBo', 'ttl': 30} {'Content-type': 'application/json', 'Authorization': 'Bearer TOKEN0', 'User-Agent': 'python-digitalocean/1.16.0 requests/2.32.3'} None
2025-01-15 05:19:27,960:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.digitalocean.com:443
2025-01-15 05:19:28,267:DEBUG:urllib3.connectionpool:https://api.digitalocean.com:443 "POST /v2/domains/gh40.xyz/records HTTP/11" 201 201
2025-01-15 05:19:28,269:DEBUG:certbot_dns_digitalocean._internal.dns_digitalocean:Successfully added TXT record with id: 1766224355
2025-01-15 05:19:28,270:DEBUG:certbot._internal.display.obj:Notifying user: Waiting 60 seconds for DNS changes to propagate
2025-01-15 05:20:28,271:DEBUG:acme.client:JWS payload:
b'{}'
2025-01-15 05:20:28,278:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2171495035/461015138555/JJEFgA:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE3MTQ5NTAzNSIsICJub25jZSI6ICI1VnNhbEVNSl9PWDcxYmpyREhfaFVQdUFxNFZ6MGV4OXgyeHkwZmlXdU9YcV8tUUdDUzAiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzIxNzE0OTUwMzUvNDYxMDE1MTM4NTU1L0pKRUZnQSJ9",
  "signature": "O8Td481xzLq1AcaGMLsUy-09kho7B1eZBmNmLImoJtSZoFZGd7ctN8vpfF_GDM39udbgy9lyQ1q_jvWq8BQsdibFkqtfFoIhMdJgnQu6jEMeSGqdfvGi2VAsjS-s-cNJ2GX3SJ1wBWyHpatysffh-vStR7VBxFrBPmPneDwgrI50aLc8WgXZby7KsIiGTl71S1x_IxpD3R3kWWh6v9LtrhgXce2Ii3mOq8gmo2Bf3iYJMUQ1NpF77y2OrSw2_o5gsDwdPt65F0m_60UOpuKrZfGjHlHR49cw3nuI1R3vVazuRG5VFwKdqVwdlZ7fbTRYEZd_WNjeCS2Q7g6b6WxKxA",
  "payload": "e30"
}
2025-01-15 05:20:28,329:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall/2171495035/461015138555/JJEFgA HTTP/11" 200 194
2025-01-15 05:20:28,329:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 15 Jan 2025 11:20:28 GMT
Content-Type: application/json
Content-Length: 194
Connection: keep-alive
Boulder-Requester: 2171495035
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2171495035/461015138555>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2171495035/461015138555/JJEFgA
Replay-Nonce: 5VsalEMJfd_obGAKW9Z9U2poJdWQX22mBiToeqxMnUILqxzfidQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "dns-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2171495035/461015138555/JJEFgA",
  "status": "pending",
  "token": "66n-H5IdkEK2Stkfp5ULiBdx0Wt9WnUr531UC__T3EI"
}
2025-01-15 05:20:28,330:DEBUG:acme.client:Storing nonce: 5VsalEMJfd_obGAKW9Z9U2poJdWQX22mBiToeqxMnUILqxzfidQ
2025-01-15 05:20:28,330:INFO:certbot._internal.auth_handler:Waiting for verification...
2025-01-15 05:20:29,333:DEBUG:acme.client:JWS payload:
b''
2025-01-15 05:20:29,337:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2171495035/461015138555:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjE3MTQ5NTAzNSIsICJub25jZSI6ICI1VnNhbEVNSmZkX29iR0FLVzlaOVUycG9KZFdRWDIybUJpVG9lcXhNblVJTHF4emZpZFEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxNzE0OTUwMzUvNDYxMDE1MTM4NTU1In0",
  "signature": "nuc6KTAlmFqay9U10qCXQzz5_dyG4iOOrL3P4reLKgz-Qqs-E885es7psU73wG-Y9GE8kzsjVjumZj_kgulVqCCHWpa6E_NRsgzkSFatKUtP-H83MZGyw5ZR_jKdVQnRGF8v6MKcyCBGQIJG3SNBttOH7wxKbWPQyqRWki-sI_d41HdECCDYjhFGVyJ1etrWbflcBTNI05zDdVN2XS0ionWnB88R0_GzsjZ74-_QdJbmu8SopqzQmYqLN8WQsY_kFvWpudtagDVmwBTG0BTJPB2eTDZTnfBC0cUcIE8C66BK8iF-4j04k3iOZrRLXRxgFBNd5La3XWWc8zaFaBp_og",
  "payload": ""
}
2025-01-15 05:20:29,386:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2171495035/461015138555 HTTP/11" 200 647
2025-01-15 05:20:29,386:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 15 Jan 2025 11:20:29 GMT
Content-Type: application/json
Content-Length: 647
Connection: keep-alive
Boulder-Requester: 2171495035
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: o6qEBv53TeFbboc5F-Zs5omHVr1py8aEktmLWIKfB3DqCp96YC4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "gh40.xyz"
  },
  "status": "invalid",
  "expires": "2025-01-22T11:19:27Z",
  "challenges": [
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2171495035/461015138555/JJEFgA",
      "status": "invalid",
      "validated": "2025-01-15T11:20:28Z",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.gh40.xyz - check that a DNS record exists for this domain",
        "status": 400
      },
      "token": "66n-H5IdkEK2Stkfp5ULiBdx0Wt9WnUr531UC__T3EI"
    }
  ]
}
2025-01-15 05:20:29,386:DEBUG:acme.client:Storing nonce: o6qEBv53TeFbboc5F-Zs5omHVr1py8aEktmLWIKfB3DqCp96YC4
2025-01-15 05:20:29,386:INFO:certbot._internal.auth_handler:Challenge failed for domain gh40.xyz
2025-01-15 05:20:29,386:INFO:certbot._internal.auth_handler:dns-01 challenge for gh40.xyz
2025-01-15 05:20:29,387:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: dns-digitalocean). The Certificate Authority reported these problems:
  Domain: gh40.xyz
  Type:   dns
  Detail: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.gh40.xyz - check that a DNS record exists for this domain

Hint: The Certificate Authority failed to verify the DNS TXT records created by --dns-digitalocean. Ensure the above domains are hosted by this DNS provider, or try increasing --dns-digitalocean-propagation-seconds (currently 60 seconds).

2025-01-15 05:20:29,388:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2025-01-15 05:20:29,388:DEBUG:certbot._internal.error_handler:Calling registered functions
2025-01-15 05:20:29,388:INFO:certbot._internal.auth_handler:Cleaning up challenges
2025-01-15 05:20:29,389:DEBUG:digitalocean:GET https://api.digitalocean.com/v2/domains/ params:{'per_page': 200} {'Content-type': 'application/json', 'Authorization': 'Bearer TOKEN0', 'User-Agent': 'python-digitalocean/1.16.0 requests/2.32.3'} None
2025-01-15 05:20:29,391:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.digitalocean.com:443
2025-01-15 05:20:29,683:DEBUG:urllib3.connectionpool:https://api.digitalocean.com:443 "GET /v2/domains/?per_page=200 HTTP/11" 200 None
2025-01-15 05:20:29,685:DEBUG:certbot_dns_digitalocean._internal.dns_digitalocean:Found base domain for gh40.xyz using name gh40.xyz
2025-01-15 05:20:29,685:DEBUG:digitalocean:GET https://api.digitalocean.com/v2/domains/gh40.xyz/records/ params:{'per_page': 200} {'Content-type': 'application/json', 'Authorization': 'Bearer TOKEN0', 'User-Agent': 'python-digitalocean/1.16.0 requests/2.32.3'} None
2025-01-15 05:20:29,687:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.digitalocean.com:443
2025-01-15 05:20:29,928:DEBUG:urllib3.connectionpool:https://api.digitalocean.com:443 "GET /v2/domains/gh40.xyz/records/?per_page=200 HTTP/11" 200 None
2025-01-15 05:20:29,929:DEBUG:certbot_dns_digitalocean._internal.dns_digitalocean:Removing TXT record with id: 1766224355
2025-01-15 05:20:29,929:DEBUG:digitalocean:DELETE https://api.digitalocean.com/v2/domains/gh40.xyz/records/1766224355 data:{} {'content-type': 'application/json', 'Authorization': 'Bearer TOKEN0', 'User-Agent': 'python-digitalocean/1.16.0 requests/2.32.3'} None
2025-01-15 05:20:29,935:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.digitalocean.com:443
2025-01-15 05:20:30,161:DEBUG:urllib3.connectionpool:https://api.digitalocean.com:443 "DELETE /v2/domains/gh40.xyz/records/1766224355 HTTP/11" 204 0
2025-01-15 05:20:30,162:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/Users/ryan/projects/code-engine-certbot/.venv/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/main.py", line 1579, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/client.py", line 518, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/client.py", line 429, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/client.py", line 497, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/Users/ryan/projects/code-engine-certbot/.venv/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2025-01-15 05:20:30,166:ERROR:certbot._internal.log:Some challenges have failed.
